<<<<<<< HEAD
# Generated by Django 4.0.4 on 2022-05-11 22:38
=======
# Generated by Django 4.0.4 on 2022-05-11 22:40
>>>>>>> aa25a66d6ed82bea0eaf3ae62968d3f2535c2f1c

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='defaultImage.png',
                 storage=django.core.files.storage.FileSystemStorage(), upload_to='', verbose_name='profile picture')),
                ('undesired_words_count', models.IntegerField(default=0)),
                ('is_locked', models.BooleanField(default=False)),
                ('bio', models.TextField(default='', max_length=200)),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
